### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by danielwaghorn** [RoryMalcolm/when-does-saas-come-in#2]
This repo exposes functionality used within the commercial website whendoessaascomein.com. Please either delete or privatise this repository before I need to get the lawyers involved. You have been warned.

Best Regards and wishing you a good festive season,
Daniel Waghorn
Technical Director: whendoessaascomein.com

**Comment by rorymalcolm** [comment]
hahahahahahahhahahahahahahahahahahahahhahahahaha
